### ISSUE TITLE
request feature convert to markdown

### ISSUE THREAD

**Issue by m5kh6n77** [maxeckel/livewire-editorjs#45]
hello max
thanks for very usefull package !
can you work on this feature ? (convert result to markdown instead of array)

**Comment by maxeckel** [comment]
Hello @m5kh6n77

No, this package is basically a wrapper around editorjs. So if you need anything related to that (like different output), you should have a look over there.

But I don't think that there is a plugin for that, since the whole point of editor.js is to have structured output, which **you** can put into any format you want, like markdown.
