### ISSUE TITLE
Adding custom plugins

### ISSUE THREAD

**Issue by moazam1** [maxeckel/livewire-editorjs#7]
Hi, great work. Right on time when needed!

I would like to add couple plugins from editorjs and also I built a custom plugin located public/js/editorjs/myplugin. How can I load those plugins?

I would love to see more examples in the doc. 

Thank you for your hard work!

**Comment by maxeckel** [comment]
Hey @moazam1,

you will have to publish the raw assets for the editor using:

```php artisan vendor:publish --tag=livewire-editorjs:assets:raw```

For adding the plugins and your custom plugin, you would need to refer to the corresponding documentation. 
But the normal "flow" would be to import the plugins into:

`resources/js/vendor/livewire-editorjs/editorjs.js`

And adding them to the tools section of the editor initializer.

As stated in the docs be aware: 

**When publishing the raw assets you will need to install all the plugins (which are included by default) yourself.**

Otherwise, you will (of course) get errors when trying to compile it.

I might add a command (similar to jetstream) to install these things automatically, but sadly at the time of writing, this isn't included yet.

Hope this helps you! If you need any further assistance, feel free to reach out!

**Comment by moazam1** [comment]
@maxeckel thanks so much. I will let you know if I run into any issue.
